# some vars are defind in travis repo
sudo: required
branches:
    only:
        - master
        - ci-integration
        - dev
language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
-services:
  - docker
env:
  - apiname="apiserver:latest"
  - NODE_VERSION="10"
before_install:
  - nvm install $NODE_VERSION
##   - . heroku.sh
before_script:
  - get -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
script:
  - docker build -t $apiname -f searchAPI/Dockerfile .
  - docker rmi -f $(docker images -f "dangling=true" -q)
  - docker tag "$apiname" registry.heroku.com/$HROKU_APP_NAME/web
deploy:
  provider: script
  script:
    docker push $apiname;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  branch: master
